apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shinyproxy.resourcename" . }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "shinyproxy.resourcename" . }}
  namespace: {{ default .Release.Namespace .Values.proxy.kubernetes.namespace }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods","persistentvolumeclaims"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods/log"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "shinyproxy.resourcename" . }}
  namespace: {{ default .Release.Namespace .Values.proxy.kubernetes.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "shinyproxy.resourcename" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "shinyproxy.resourcename" . }}
