kind: Secret
apiVersion: v1
metadata:
  name: {{ include "shinyproxy.resourcename" . }}
  labels:
    {{- include "shinyproxy.labels" . | nindent 4 }}
type: Opaque
data:
{{- $values := pick .Values "proxy" "spring" }}
{{- $_ := set $values "proxy" (pick $values.proxy "ldap" "kerberos" "keycloak" "openid" "saml" "social" "users") }}
{{- $_ := set $values "spring" (pick $values.spring "redis") }}
  secrets.json: {{ $values | toJson | b64enc | quote }}
