apiVersion: v1
kind: Service
metadata:
  name: {{ include "shinyproxy.resourcename" . }}
  labels:
    {{- include "shinyproxy.labels" . | nindent 4 }}
  {{- if .Values.proxy.service.annotations }}
  annotations:
    {{- .Values.proxy.service.annotations | toYaml | trimSuffix "\n" | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  {{- if .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
  selector:
      {{- include "shinyproxy.selectorLabels" . | nindent 6 }}
  ports:
    - port: 8080
      targetPort: 8080
      {{- if .Values.proxy.service.ports.nodePort }}
      nodePort: {{ .Values.proxy.service.ports.nodePort }}
      {{- end }}

